package home;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.stream.Collectors;

public class Researches {

	    ArrayList<String> words = new ArrayList<>(
	            Arrays.asList("Cybersecurity Issues among High School Students: A Thematic Review (2023)\r\n"
	            		+ "DOI: 10.9101/ijkl.1122\r\n"
	            		, "A Structural Equation Approach and Modelling of Pre-service Teachers' Perspectives of \nCybersecurity Education (2023)\r\n"
	            		+ "DOI: 10.5522/qrst.4455\r\n"
	            		, "A Review: Human Factor and Cybersecurity (2023)\r\n"
	            		+ "DOI: 10.7766/uvwx.8899\r\n"
	            		, "High-Resolution Modeling and Analysis of Cryptocurrency Mining’s Impact on Power Grids: Carbon \nFootprint, Reliability, and Electricity Price (2023)\r\n"
	            		+ "DOI: 10.4444/ijkl.8888\r\n"
	            		, "Long Memory in the High Frequency Cryptocurrency Markets Using Fractal Connectivity Analysis: \nThe Impact of COVID-19 (2023)\r\n"
	            		+ "DOI: 10.5555/mnop.9999\r\n"
	            		, "Ethical Principles for Artificial Intelligence in Education (2023)\r\n"
	            		+ "DOI: 10.9999/abcd.4444\r\n"
	            		, "Implementation of Artificial Intelligence in Agriculture (2023)\r\n"
	            		+ "DOI: 10.7766/yzzz.1111 \r\n"
	            		+ "\r\n"
	            		, "SOK: Young Children's Cybersecurity Knowledge, Skills \\& Practice: A Systematic Literature Review (2022)\r\n"
	            		+ "DOI: 10.3344/mnop.7788\r\n"
	            		, "Immersive Technology: A Meta-Analysis of Augmented/Virtual Reality Applications and Their Impact \n on Tourism Experience (2022) \r\n"
	            		+ "DOI: 10.9999/uvwx.6666\r\n"
	            		, "Spillover and Quantitative Link Between Cryptocurrency Shocks and Stock Returns: New Evidence \nFrom G7 Countries (2022)\r\n"
	            		+ "DOI: 10.5522/mnop.2222\r\n"
	            		, "The Impact of Cryptocurrency Over the Turkish Capital Market: A Case Study of Bitcoin (BTC) (2022)\r\n"
	            		+ "DOI: 10.7766/qrst.3333\r\n"
	            		, "Sustainable Cryptocurrency Adoption Assessment Among IT Enthusiasts and Cryptocurrency Social \nCommunities (2022)\r\n"
	            		+ "DOI: 10.1111/yzzz.5555\r\n"
	            		, "The Adoption of Cryptocurrency as a Disruptive Force: Deep Learning-Based Dual Stage Structural \nEquation Modeling and Artificial Neural Network Analysis (2022)\r\n"
	            		+ "DOI: 10.2222/abcd.6666\r\n"
	            		, "An Automated Cryptocurrency Trading System Based on the Detection of Unusual Price M\r\n"
	            		+ "Movements with a Time-Series Clustering-Based Approach (2022)\r\n"
	            		+ "DOI: 10.3333/efgh.7777\r\n"
	            		, "The Importance of Cybersecurity Education in School (2021)\r\n"
	            		+ "DOI: 10.1234/abcd.5678\r\n"
	            		, "Cybersecurity Awareness Among the Youngs in Malaysia by Gamification (2021)\r\n"
	            		+ "DOI: 10.5678/efgh.1234\r\n"
	            		, "Influence of Human Factors on Cybersecurity Within Healthcare Organizations: A Systematic \nReview (2021)\r\n"
	            		+ "DOI: 10.3333/ijkl.4444\r\n"
	            		, "The Role of the Internet of Things in Healthcare: Future Trends and Challenges  (2021)\r\n"
	            		+ "DOI: 10.9988/efgh.8888\r\n"
	            		, "Internet of Things (IoT): A Review of Its Enabling Technologies in Healthcare Applications, \nStandards Protocols, Security, and Market Opportunities  (2021)\r\n"
	            		+ "DOI: 10.2222/mnop.1111\r\n"
	            		, "The Impact of Cyber-Attacks on Cryptocurrency Price, Return, and Liquidity: Evidence from \nQuantile-on-Quantile Regression (2021)\r\n"
	            		+ "DOI: 10.9988/uvwx.4444\r\n"
	            		, "Agriculture Development Pesticide Application and Its Impact on the Environment (2021)\r\n"
	            		+ "DOI: 10.9988/abcd.2222\r\n"
	            		, "Current progress and Future Prospects of Agriculture Technology: Gateway to Sustainable \nAgriculture (2021)\r\n"
	            		+ "DOI: 10.5555/uvwx.7777\r\n"
	            		, "Cyber risk and cybersecurity: a systematic review of data availability (2020)\r\n"
	            		+ "DOI: 10.9988/yzzz.3344\r\n"
	            		, "Application of Internet of Things and Virtual Reality Technology in College Physical Education  (2020)\r\n"
	            		+ "DOI: 10.5555/yzzz.4444\r\n"
	            		, "Enhancement of Educational Services by Using the Internet of Things Applications for Talent and \nIntelligent Schools  (2020)\r\n"
	            		+ "DOI: 10.6666/abcd.5555\r\n"
	            		, "Robotics, Smart Wearable Technologies, and Autonomous Intelligent Systems for \nHealthcare During the COVID-19 Pandemic: An Analysis of the State of the Art and Future Vision  (2020)\r\n"
	            		+ "DOI: 10.9101/yzzz.2222\r\n"
	            		+ "\r\n"
	            		, "The Impact of Artificial Intelligence and Robotics on the Future Employment Opportunities  (2020)\r\n"
	            		+ "DOI: 10.7766/ijkl.5555\r\n"
	            		, "Artificial Intelligence in Education: A Review (2020)\r\n"
	            		+ "DOI: 10.6666/qrst.1111\r\n"
	            		, "Challenges and Future Directions of Big Data and Artificial Intelligence in Education (2020)\r\n"
	            		+ "DOI:10.8888/yzzz.3333\r\n"
	            		, "Explainability for Artificial Intelligence in Healthcare: A Multidisciplinary Perspective (2020)\r\n"
	            		+ "DOI: 10.5678/ijkl.6666\r\n"
	            		, "Leveraging Artificial Intelligence in Business: Implications, Applications and Methods (2020)\r\n"
	            		+ "DOI: 10.3344/qrst.8888\r\n"
	            		, "Artificial Intelligence and Business Models in the Sustainable Development \r\n"
	            		+ "Goals Perspective: A Systematic Literature Review (2020)\r\n"
	            		+ "DOI: 10.5522/uvwx.9999\r\n"
	            		, "Organic and Inorganic Fertilizer Contaminants in Agriculture: Impact on Soil and Water \r\n"
	            		+ "Resources (2020)\r\n"
	            		+ "DOI: 10.1111/efgh.3333\r\n"
	            		, "Increasing the Effectiveness of Cybersecurity Teaching and Learning By Applying Activity Theory and Narrative Research (2019)\r\n"
	            		+ "DOI: 10.1111/abcd.2222\r\n"
	            		, "Securing the Human: A Review of Literature on Broadening Diversity in Cybersecurity Education (2019)\r\n"
	            		+ "DOI: 10.2222/efgh.3333\r\n"
	            		, "Augmented Reality Marketing: How Mobile AR-Apps Can Improve Brands Through Inspiration (2019)\r\n"
	            		+ "DOI: 10.5678/abcd.8888\r\n"
	            		, "Cryptocurrency Market Contagion: Market Uncertainty, Market Complexity, and Dynamic Portfolios (2019)\r\n"
	            		+ "DOI: 10.9101/efgh.9999\r\n"
	            		, "Artificial Intelligence in Education: Challenges and Opportunities for Sustainable Development (2019)\r\n"
	            		+ "DOI: 10.7777/uvwx.2222\r\n"
	            		, "Artificial Intelligence in Healthcare: A Critical Analysis of the Legal and \r\n"
	            		+ "Ethical Implications (2019)\r\n"
	            		+ "DOI: 10.9101/mnop.7777\r\n"
	            		, "Demystifying Data Science Projects: A Look on the People and Process of Data Science Today  (2018)\r\n"
	            		+ "DOI: 10.5678/mnop.3333\r\n"
	            		, "Internet of Things security and forensics: Challenges and Opportunities  (2018)\r\n"
	            				+ "DOI: 10.5522/yzzz.6666\r\n"
	            		, "Internet of Things (IoT) and Entrepreneurship Education: Opportunities and Challenges  (2018)\r\n"
	            				+ "DOI: 10.7777/efgh.6666\r\n"
	            		, "Systematic Review of Research Trends in Robotics Education for Young Children  (2018)\r\n"
	            				+ "DOI: 10.8888/ijkl.7777\r\n"
	            		, "Ethical Governance is Essential to Building Trust in Robotics and Artificial Intelligence Systems  (2018)\r\n"
	            				+ "DOI: 10.3344/abcd.3333\r\n"
	            		, "A Systematic Review on Teaching and Learning Robotics Content Knowledge in K-12  (2018)\r\n"
	            				+ "DOI: 10.5522/efgh.4444\r\n"
	            		, "The Impact of Using Augmented Reality Technology in The Solar System and Beyond Unit on The \nAcademic Achievement of The Students (2018)\r\n"
	            				+ "DOI: 10.6666/ijkl.3333\r\n"
	            		, "Investigating the Impact of Real-World Environments on the Perception of 2D Visualizations in \nAugmented Reality (2018)\r\n"
	            				+ "DOI: 10.8888/qrst.5555\r\n"
	            		, "Role of Marine Macroalgae in Plant Protection \\& Improvement for Sustainable Agriculture \nTechnology (2018)\r\n"
	            				+ "DOI: 10.6666/yzzz.8888\r\n"
	            		, "Machine Learning Algorithms: Popular Algorithms for Data Science and Machine Learning (2017)\r\n"
	            				+ "DOI: 10.8888/abcd.9999\r\n"
	            		, "Data Science Efficient Healthcare and Medical Systems: A Techno-Managerial Perspective  (2017)\r\n"
	            				+ "DOI: 10.9999/efgh.1111\r\n"
	            		, "Trust in Data Science: Collaboration, Translation, and Accountability in Corporate Data Science \nProjects  (2017)\r\n"
	            				+ "DOI: 10.1234/ijkl.2222\r\n"
	            		, "Comparing Data Science Project Management Methodologies via a Controlled Experiment  (2017)\r\n"
	            				+ "DOI: 10.9101/qrst.4444\r\n"
	            		, "Internet of Things for Smart Healthcare: Technologies, Challenges, and Opportunities  (2017)\r\n"
	            				+ "DOI: 10.7766/abcd.7777\r\n"
	            		, "The Impact of Internet-of-Things in Higher Education  (2017)\r\n"
	            				+ "DOI: 10.3333/qrst.2222\r\n"
	            		, "Internet of Things Architecture: Recent Advances, Taxonomy, Requirements, and Open Challenges \n (2017)\r\n"
	            				+ "DOI: 10.4444/uvwx.3333\r\n"
	            		, "Impact of Robotics on Manufacturing: A Longitudinal Machine Learning Perspective  (2017)\r\n"
	            				+ "DOI: 10.1234/qrst.9999\r\n"
	            		, "Automation of a Business Process Using Robotic Process Automation (RPA): A Case Study (2017)\r\n"
	            				+ "DOI: 10.9988/mnop.6666\r\n"
	            		, "Analysis of the Revolution in Business Efficiency Associated with the Use of Robotics as a Part \nof Handling Activities and Operations  (2017)\r\n"
	            				+ "DOI: 10.1111/qrst.7777\r\n"
	            		, "Advantages and Challenges Associated with Augmented Reality for Education: A Systematic Review \nof the Literature (2017)\r\n"
	            				+ "DOI: 10.4444/abcd.1111\r\n"
	            		, "Artificial Intelligence in Healthcare: Past, Present and Future (2017)\r\n"
	            				+ "DOI: 10.1234/efgh.5555\r\n"
	            		, "Modern Agricultural Technology Adoption its Importance, Role and Usage for the \r\n"
	            				+ "Improvement of Agriculture (2016)\r\n"
	            				+ "DOI: 10.9999/ijkl.2222\r\n"
	            		, "Agriculture and Its Impact on Land-Use Environment and Ecosystem Services (2016)\r\n"
	            				+ "DOI: 10.3333/mnop.5555\r\n"
	            		, "Augmented Reality: Research Agenda for Studying the Impact of Its Media Characteristics on \nConsumer Behaviour (2016)\r\n"
	            				+ "DOI: 10.5555/efgh.2222\r\n"
	            		, "Use of Internet of Things (IoT) in Healthcare: A Survey  (2016)\r\n"
	            				+ "DOI: 10.1111/ijkl.9999\r\n"
	            		, " A Review of Research on Augmented Reality in Education: Advantages and Applications (2015)\r\n"
	            				+ "DOI: 10.3333/yzzz.9999\r\n"
	            		, "Tourists Responses to Mobile Augmented Reality Travel Guides: The Role of Emotions on Adoption \nBehavior (2015)\r\n"
	            				+ "DOI: 10.1234/yzzz.7777\r\n"
	            		, "Data Quality for Data Science, Predictive Analytics, and Big Data in Supply Chain Management: \nAn Introduction to the Problem and Suggestions for Research and Applications (2014)\r\n"
	            				+ "DOI: 10.5555/qrst.6666\r\n"
	            		, "Big Data, Data Science, and Analytics: The Opportunity and Challenge for IS Research  (2014)\r\n"
	            				+ "DOI: 10.7777/yzzz.8888\r\n"
	            		, "The Impact of Robotics on Employment and Motivation of Employees in the Service Sector with \nSpecial Reference to Healthcare  (2014)\r\n"
	            				+ "DOI: 10.9999/mnop.8888\r\n"
	            		, "The Impact of Educational Robotics on Student STEM Learning, Attitudes, and Workplace Skills\r\n"
	            				+ " (2014)\r\n"
	            				+ "DOI: 10.5678/uvwx.1111\r\n"
	            		, "Data Science and its Relationship to Big Data and Data-Driven Decision-Making (2013)\r\n"
	            				+ "DOI: 10.4444/mnop.5555\r\n"
	            		, "The Quantified Self: Fundamental Disruption in Big Data Science and Biological Discovery (2013)\r\n"
	            				+ "DOI: 10.6666/uvwx.7777\r\n"
	            		, "Using Plastic Bags and Its Damaging Impact on Environment and Agriculture: An Alternative \r\n"
	            				+ "Proposal (2013)\r\n"
	            				+ "DOI: 10.2222/ijkl.4444\r\n"
	            		, "Use of Pesticides in Agriculture and Livestock Animals and Its Impact on Environment of India (2013)\r\n"
	            				+ "DOI: 10.4444/qrst.6666\r\n"
	            		, "Augmented Reality in Education: Current Technologies and the Potential for Education (2012)\r\n"
	            				+ "DOI: 10.2222/uvwx.8888\r\n"
	            		, "Urbanization in the Philippines and Its Influence on Agriculture (2007)\r\n"
	            				+ "DOI: 10.7777/abcd.9999\r\n"
	            		, "Precision Farming--The Emerging Concept of Agriculture for Today and Tomorrow (2000)\r\n"
	            				+ "DOI: 10.8888/efgh.1111\r\n"
	            				+ "")
	    );
	    
	    public List<String> getWords() {
	        return words;
	    }
	}


